# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import coalition_service.coalition_service_pb2 as coalition__service__pb2


class CoalitionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.set_coalition_member = channel.unary_unary(
                '/coalition_service.CoalitionService/set_coalition_member',
                request_serializer=coalition__service__pb2.SetCoalitionMemberRequest.SerializeToString,
                response_deserializer=coalition__service__pb2.SetCoalitionMemberResponse.FromString,
                )


class CoalitionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def set_coalition_member(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoalitionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'set_coalition_member': grpc.unary_unary_rpc_method_handler(
                    servicer.set_coalition_member,
                    request_deserializer=coalition__service__pb2.SetCoalitionMemberRequest.FromString,
                    response_serializer=coalition__service__pb2.SetCoalitionMemberResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coalition_service.CoalitionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CoalitionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def set_coalition_member(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coalition_service.CoalitionService/set_coalition_member',
            coalition__service__pb2.SetCoalitionMemberRequest.SerializeToString,
            coalition__service__pb2.SetCoalitionMemberResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
