# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import coalition_service.coalition_service_pb2 as coalition__service__pb2


class CoalitionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.set_coalition_member = channel.unary_unary(
                '/coalition_service.CoalitionService/set_coalition_member',
                request_serializer=coalition__service__pb2.SetCoalitionMemberRequest.SerializeToString,
                response_deserializer=coalition__service__pb2.SetCoalitionMemberResponse.FromString,
                )
        self.reset_all_members = channel.unary_unary(
                '/coalition_service.CoalitionService/reset_all_members',
                request_serializer=coalition__service__pb2.Empty.SerializeToString,
                response_deserializer=coalition__service__pb2.Empty.FromString,
                )
        self.get_member_by_tg_id = channel.unary_unary(
                '/coalition_service.CoalitionService/get_member_by_tg_id',
                request_serializer=coalition__service__pb2.GetMemberByTgIdRequest.SerializeToString,
                response_deserializer=coalition__service__pb2.GetMemberByTgIdResponse.FromString,
                )
        self.set_tg_id_by_key = channel.unary_unary(
                '/coalition_service.CoalitionService/set_tg_id_by_key',
                request_serializer=coalition__service__pb2.SetTgIdByKeyRequest.SerializeToString,
                response_deserializer=coalition__service__pb2.SetTgIdByKeyResponse.FromString,
                )
        self.get_members = channel.unary_unary(
                '/coalition_service.CoalitionService/get_members',
                request_serializer=coalition__service__pb2.GetMembersRequest.SerializeToString,
                response_deserializer=coalition__service__pb2.GetMembersResponse.FromString,
                )


class CoalitionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def set_coalition_member(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def reset_all_members(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_member_by_tg_id(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def set_tg_id_by_key(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_members(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoalitionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'set_coalition_member': grpc.unary_unary_rpc_method_handler(
                    servicer.set_coalition_member,
                    request_deserializer=coalition__service__pb2.SetCoalitionMemberRequest.FromString,
                    response_serializer=coalition__service__pb2.SetCoalitionMemberResponse.SerializeToString,
            ),
            'reset_all_members': grpc.unary_unary_rpc_method_handler(
                    servicer.reset_all_members,
                    request_deserializer=coalition__service__pb2.Empty.FromString,
                    response_serializer=coalition__service__pb2.Empty.SerializeToString,
            ),
            'get_member_by_tg_id': grpc.unary_unary_rpc_method_handler(
                    servicer.get_member_by_tg_id,
                    request_deserializer=coalition__service__pb2.GetMemberByTgIdRequest.FromString,
                    response_serializer=coalition__service__pb2.GetMemberByTgIdResponse.SerializeToString,
            ),
            'set_tg_id_by_key': grpc.unary_unary_rpc_method_handler(
                    servicer.set_tg_id_by_key,
                    request_deserializer=coalition__service__pb2.SetTgIdByKeyRequest.FromString,
                    response_serializer=coalition__service__pb2.SetTgIdByKeyResponse.SerializeToString,
            ),
            'get_members': grpc.unary_unary_rpc_method_handler(
                    servicer.get_members,
                    request_deserializer=coalition__service__pb2.GetMembersRequest.FromString,
                    response_serializer=coalition__service__pb2.GetMembersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coalition_service.CoalitionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CoalitionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def set_coalition_member(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coalition_service.CoalitionService/set_coalition_member',
            coalition__service__pb2.SetCoalitionMemberRequest.SerializeToString,
            coalition__service__pb2.SetCoalitionMemberResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def reset_all_members(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coalition_service.CoalitionService/reset_all_members',
            coalition__service__pb2.Empty.SerializeToString,
            coalition__service__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_member_by_tg_id(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coalition_service.CoalitionService/get_member_by_tg_id',
            coalition__service__pb2.GetMemberByTgIdRequest.SerializeToString,
            coalition__service__pb2.GetMemberByTgIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def set_tg_id_by_key(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coalition_service.CoalitionService/set_tg_id_by_key',
            coalition__service__pb2.SetTgIdByKeyRequest.SerializeToString,
            coalition__service__pb2.SetTgIdByKeyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_members(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coalition_service.CoalitionService/get_members',
            coalition__service__pb2.GetMembersRequest.SerializeToString,
            coalition__service__pb2.GetMembersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
