# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coalition_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63oalition_service.proto\x12\x11\x63oalition_service\"\x07\n\x05\x45mpty\"B\n\x19SetCoalitionMemberRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x16\n\x0eschool_user_id\x18\x02 \x01(\t\"X\n\x1aSetCoalitionMemberResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x15\n\ris_new_member\x18\x03 \x01(\x08\x32\xd4\x01\n\x10\x43oalitionService\x12u\n\x14set_coalition_member\x12,.coalition_service.SetCoalitionMemberRequest\x1a-.coalition_service.SetCoalitionMemberResponse\"\x00\x12I\n\x11reset_all_members\x12\x18.coalition_service.Empty\x1a\x18.coalition_service.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coalition_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=46
  _globals['_EMPTY']._serialized_end=53
  _globals['_SETCOALITIONMEMBERREQUEST']._serialized_start=55
  _globals['_SETCOALITIONMEMBERREQUEST']._serialized_end=121
  _globals['_SETCOALITIONMEMBERRESPONSE']._serialized_start=123
  _globals['_SETCOALITIONMEMBERRESPONSE']._serialized_end=211
  _globals['_COALITIONSERVICE']._serialized_start=214
  _globals['_COALITIONSERVICE']._serialized_end=426
# @@protoc_insertion_point(module_scope)
